-- Complete starter content. Run after schema.sql. Replace placeholder contact details in the CMS after login.

insert into public.site_settings (id,site_name,phone,email,address,logo,favicon,footer_text,facebook,linkedin,instagram,seo_title,seo_description) values
('00000000-0000-0000-0000-000000000001','New Era Computer Training Centre','+27 41 000 0000','info@neweratraining.co.za','Port Elizabeth (Gqeberha), Eastern Cape, South Africa','/images/new-era-logo.svg','/favicon.ico','Professional computer training and skills development for individuals and organisations in Gqeberha.','','','','New Era Computer Training Centre | Computer Courses in Port Elizabeth','Professional computer training, Microsoft courses and skills development programmes for students, employees and organisations in Port Elizabeth (Gqeberha).')
on conflict (id) do update set site_name=excluded.site_name, phone=excluded.phone, email=excluded.email, address=excluded.address, logo=excluded.logo, favicon=excluded.favicon, footer_text=excluded.footer_text, seo_title=excluded.seo_title, seo_description=excluded.seo_description;

insert into public.course_categories (id,name,slug,description) values
('10000000-0000-0000-0000-000000000001','Computer Literacy','computer-literacy','Build the essential digital confidence needed for everyday study and work.'),
('10000000-0000-0000-0000-000000000002','Microsoft Courses','microsoft-courses','Practical Microsoft Office training for modern workplaces.'),
('10000000-0000-0000-0000-000000000003','Business Skills','business-skills','Develop organised, workplace-ready administrative and project skills.'),
('10000000-0000-0000-0000-000000000004','Corporate Training','corporate-training','Custom group programmes for teams, schools and organisations.')
on conflict (id) do nothing;

insert into public.courses (id,title,slug,excerpt,description,duration,requirements,learning_outcomes,who_should_attend,benefits,faqs,category_id,featured_image,og_image,is_featured,seo_title,seo_description) values
('20000000-0000-0000-0000-000000000001','Computer Literacy','computer-literacy','A practical introduction to computers, the internet, email and essential office applications.','This foundational programme helps learners become confident computer users. Training is practical, instructor-led and suitable for beginners who want workplace-ready digital skills.','5 days','["No previous computer experience required","Basic English literacy"]','["Use a computer confidently","Create and manage files and folders","Use email and the internet responsibly","Complete basic tasks in common office applications"]','["First-time computer users","Job seekers","Employees needing digital confidence"]','["Practical exercises","Supportive classroom environment","Skills applicable to daily office work"]','[{"question":"Is this suitable for complete beginners?","answer":"Yes. The programme starts with the basics and builds confidence through guided practice."},{"question":"Will I use a computer during the training?","answer":"Yes. The course is designed around practical exercises."}]','10000000-0000-0000-0000-000000000001','/images/course-computer-literacy.svg','/images/course-computer-literacy.svg',true,'Computer Literacy Course in Port Elizabeth | New Era','Learn essential computer skills with practical beginner-friendly training in Port Elizabeth (Gqeberha).'),
('20000000-0000-0000-0000-000000000002','Intermediate Computer Skills','intermediate-computer-skills','Strengthen your office productivity, document management and everyday digital workflow.','Designed for learners who already understand the basics and want to improve efficiency, accuracy and confidence when working with office software and digital information.','5 days','["Basic computer literacy"]','["Improve document formatting","Manage files more efficiently","Use spreadsheets for routine workplace tasks","Apply better digital work habits"]','["Office workers","Administrative staff","Learners progressing beyond beginner level"]','["Workplace-focused practice","Improved productivity","Structured skill progression"]','[{"question":"Do I need to complete the beginner course first?","answer":"Not necessarily. Learners with basic computer skills may enrol directly."}]','10000000-0000-0000-0000-000000000001','/images/course-intermediate.svg','/images/course-intermediate.svg',true,'Intermediate Computer Skills Course | New Era Gqeberha','Improve office productivity with intermediate computer skills training in Port Elizabeth.'),
('20000000-0000-0000-0000-000000000003','Advanced Computer Skills','advanced-computer-skills','Develop advanced office application skills for more demanding workplace responsibilities.','An advanced programme for learners seeking stronger productivity, reporting and digital workflow skills for the workplace.','5 days','["Intermediate computer skills"]','["Handle more complex office tasks","Use productivity tools efficiently","Prepare professional documents and reports","Apply advanced digital workflow practices"]','["Experienced office workers","Supervisors","Administrative professionals"]','["Advanced practical exercises","Professional workflow improvement","Career-relevant skills"]','[{"question":"Who is this course for?","answer":"It is aimed at learners who already work confidently with computers and want to progress further."}]','10000000-0000-0000-0000-000000000001','/images/course-advanced.svg','/images/course-advanced.svg',true,'Advanced Computer Skills Course in Gqeberha | New Era','Build advanced workplace computer skills with professional training in Port Elizabeth.'),
('20000000-0000-0000-0000-000000000004','Microsoft Word','microsoft-word','Create, format and manage professional documents using Microsoft Word.','Learn the practical Microsoft Word skills needed to produce polished workplace documents, letters and reports.','2 days','["Basic computer literacy"]','["Format professional documents","Use tables and page layouts","Prepare letters and reports","Work efficiently with Word tools"]','["Office workers","Students","Administrative staff"]','["Hands-on document practice","Improved office readiness","Better document presentation"]','[]','10000000-0000-0000-0000-000000000002','/images/course-word.svg','/images/course-word.svg',false,'Microsoft Word Training in Port Elizabeth | New Era','Learn practical Microsoft Word skills for professional documents and reports.'),
('20000000-0000-0000-0000-000000000005','Microsoft Excel','microsoft-excel','Build practical spreadsheet skills for calculations, data organisation and reporting.','Learn how to use Microsoft Excel for everyday workplace calculations, lists, basic analysis and reporting.','3 days','["Basic computer literacy"]','["Create and format spreadsheets","Use common formulas","Organise workplace data","Prepare clear basic reports"]','["Administrative staff","Small business teams","Office workers"]','["Practical spreadsheet exercises","Workplace-ready formulas","Improved data confidence"]','[{"question":"Does the course include formulas?","answer":"Yes. Learners practise commonly used formulas and everyday spreadsheet tasks."}]','10000000-0000-0000-0000-000000000002','/images/course-excel.svg','/images/course-excel.svg',true,'Microsoft Excel Course in Port Elizabeth | New Era','Learn practical Microsoft Excel spreadsheet skills for the workplace in Gqeberha.'),
('20000000-0000-0000-0000-000000000006','Microsoft PowerPoint','microsoft-powerpoint','Create professional presentations with clear structure and effective visual communication.','This practical course teaches learners how to create, format and present effective slides for meetings and training sessions.','1 day','["Basic computer literacy"]','["Build structured slide decks","Use layouts and themes","Add images and simple charts","Present information clearly"]','["Employees","Students","Team leaders"]','["Presentation confidence","Better visual communication","Practical slide creation"]','[]','10000000-0000-0000-0000-000000000002','/images/course-powerpoint.svg','/images/course-powerpoint.svg',false,'Microsoft PowerPoint Training | New Era Port Elizabeth','Create professional presentations with practical Microsoft PowerPoint training.'),
('20000000-0000-0000-0000-000000000007','IT End User Computing','it-end-user-computing','Develop structured end-user computing skills for study, work and professional development.','A structured programme covering the practical digital knowledge and application skills needed by modern computer users.','Contact us for programme options','["Programme entry requirements are confirmed during enquiry"]','["Apply end-user computing principles","Use digital tools productively","Work with office applications","Strengthen workplace readiness"]','["Job seekers","Employees","Organisations seeking structured training"]','["Structured learning pathway","Practical digital skills","Suitable for group delivery"]','[]','10000000-0000-0000-0000-000000000001','/images/course-end-user.svg','/images/course-end-user.svg',false,'IT End User Computing Training in Gqeberha | New Era','Structured IT end user computing skills development for individuals and organisations.'),
('20000000-0000-0000-0000-000000000008','Project Management','project-management','Understand the practical principles of planning, organising and monitoring projects.','Develop practical project management awareness for better planning, communication and delivery in the workplace.','3 days','["No specialist software knowledge required"]','["Understand project stages","Set goals and milestones","Monitor tasks and responsibilities","Improve project communication"]','["Team leaders","Administrators","Employees supporting projects"]','["Practical planning methods","Clearer project communication","Improved organisation"]','[]','10000000-0000-0000-0000-000000000003','/images/course-project.svg','/images/course-project.svg',true,'Project Management Course in Port Elizabeth | New Era','Learn practical project planning and management skills for the workplace.'),
('20000000-0000-0000-0000-000000000009','Records Management','records-management','Improve the organisation, handling and retrieval of workplace records.','This programme introduces practical methods for managing records accurately and consistently in office environments.','2 days','["Suitable for administrative and support staff"]','["Organise records systematically","Improve retrieval processes","Understand record handling responsibilities","Apply practical office procedures"]','["Administrative staff","Records officers","Office support teams"]','["Better organisation","Improved information retrieval","Practical office procedures"]','[]','10000000-0000-0000-0000-000000000003','/images/course-records.svg','/images/course-records.svg',false,'Records Management Training | New Era Gqeberha','Improve workplace records organisation and retrieval with practical training.')
on conflict (id) do nothing;

insert into public.testimonials (id,name,company,review,featured) values
('30000000-0000-0000-0000-000000000001','Training Participant','Office Skills Programme','The training was practical, clear and easy to follow. I gained confidence using office applications in my daily work.',true),
('30000000-0000-0000-0000-000000000002','Corporate Client','Group Training Programme','The programme was structured around our team''s needs and delivered in a professional, supportive way.',true),
('30000000-0000-0000-0000-000000000003','Course Graduate','Computer Literacy Programme','I started as a beginner and left feeling much more comfortable using a computer for job applications and office tasks.',true)
on conflict (id) do nothing;

insert into public.blog_posts (id,title,slug,excerpt,content,featured_image,og_image,seo_title,seo_description,status,tags,category_id,created_at) values
('40000000-0000-0000-0000-000000000001','Why Computer Literacy Still Matters in the Modern Workplace','why-computer-literacy-still-matters','Digital confidence remains essential for job seekers, employees and anyone building workplace skills.','Computer literacy is more than knowing how to switch on a computer. In the workplace, it includes managing files, communicating by email, using office applications and working confidently with digital information. A structured beginner programme can help learners develop these skills through practical exercises and guided support.

For job seekers, digital confidence can make it easier to prepare documents, search for opportunities and complete online applications. For employees, the same skills support accuracy, productivity and professional communication.','/images/blog-literacy.svg','/images/blog-literacy.svg','Why Computer Literacy Matters at Work | New Era','Learn why practical computer literacy remains important for job seekers and employees.','published','["Computer Literacy","Workplace Skills"]',null,'2026-05-15T08:00:00+02:00'),
('40000000-0000-0000-0000-000000000002','How Microsoft Excel Skills Can Improve Office Productivity','excel-skills-office-productivity','Even basic spreadsheet skills can save time and improve accuracy in everyday administrative work.','Microsoft Excel is widely used for lists, calculations, budgets and basic reporting. Learning how to format spreadsheets, use common formulas and organise data can make routine office work faster and more accurate.

The best way to learn is through practical exercises that reflect real workplace tasks. Start with a clear foundation and build confidence step by step.','/images/blog-excel.svg','/images/blog-excel.svg','Excel Skills for Office Productivity | New Era','Discover how practical Excel training can improve everyday office productivity.','published','["Microsoft Excel","Office Productivity"]',null,'2026-05-05T08:00:00+02:00'),
('40000000-0000-0000-0000-000000000003','Choosing the Right Computer Course for Your Goals','choosing-the-right-computer-course','Start with your current skill level and the tasks you need to perform at work or while job seeking.','The right computer course depends on your starting point and your goals. Beginners benefit from a computer literacy foundation. Learners who already understand basic computer use may be ready for intermediate training or a focused Microsoft course.

For organisations, a group training discussion can identify skill gaps and create a programme suited to the team''s needs.','/images/blog-course-choice.svg','/images/blog-course-choice.svg','How to Choose a Computer Course | New Era','Choose the right computer training programme based on your goals and current skill level.','published','["Training Advice","Skills Development"]',null,'2026-04-20T08:00:00+02:00')
on conflict (id) do nothing;


-- After creating your admin account in Supabase Auth, authorise it with:
-- insert into public.admin_users(user_id) select id from auth.users where email='YOUR-ADMIN-EMAIL';
