import Link from 'next/link';
import { AdminHeading, buttonClass, inputClass, Panel } from '@/components/admin/admin-ui';
import { requireAdmin } from '@/lib/admin';
import { createCourse, deleteCourse, toggleFeaturedCourse } from '../actions';

export default async function Courses({ searchParams }: { searchParams: { saved?: string } }) {
  const { supabase } = await requireAdmin();
  const [{ data: coursesData }, { data: categoriesData }] = await Promise.all([supabase.from('courses').select('*,course_categories(name)').order('title'), supabase.from('course_categories').select('*').order('name')]);
  const courses = coursesData ?? []; const categories = categoriesData ?? [];
  return <div className="space-y-6"><AdminHeading title="Courses" text="Create, edit, feature and delete training programmes." />{searchParams.saved ? <p className="rounded-md bg-green-50 p-3 text-sm font-semibold text-green-800">Course saved.</p> : null}<Panel title="Add course"><form action={createCourse} className="grid gap-3 md:grid-cols-2"><input name="title" required placeholder="Course title" className={inputClass} /><input name="slug" placeholder="slug-optional" className={inputClass} /><input name="duration" placeholder="Duration" className={inputClass} /><select name="category_id" className={inputClass}><option value="">No category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="excerpt" placeholder="Short excerpt" className={inputClass} /><input name="description" placeholder="Course overview" className={inputClass} /><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="is_featured" />Featured course</label><button className={buttonClass}>Add course</button></form></Panel><Panel title="Course catalogue"><div className="grid gap-3">{courses.map((item) => <div key={item.id} className="flex flex-col justify-between gap-3 rounded-md border border-gray-200 p-3 sm:flex-row sm:items-center"><div><p className="font-bold text-gray-900">{item.title}</p><p className="text-xs text-gray-500">/{item.slug} · {item.course_categories?.name || 'Uncategorised'}</p></div><div className="flex flex-wrap gap-3"><Link href={`/admin/courses/${item.id}`} className="text-sm font-bold text-brand">Edit</Link><form action={toggleFeaturedCourse}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="featured" value={String(item.is_featured)} /><button className="text-sm font-bold text-brand">{item.is_featured ? 'Unfeature' : 'Feature'}</button></form><form action={deleteCourse}><input type="hidden" name="id" value={item.id} /><button className="text-sm font-bold text-red-700">Delete</button></form></div></div>)}</div></Panel></div>;
}
