import { notFound } from 'next/navigation';
import { AdminHeading, buttonClass, inputClass, Panel } from '@/components/admin/admin-ui';
import { requireAdmin } from '@/lib/admin';
import { updateCourse } from '../../actions';

function toLines(value: unknown) { return Array.isArray(value) ? value.join('\n') : ''; }
export default async function EditCourse({ params }: { params: { id: string } }) {
  const { supabase } = await requireAdmin();
  const [{ data: course }, { data: categoriesData }] = await Promise.all([supabase.from('courses').select('*').eq('id', params.id).maybeSingle(), supabase.from('course_categories').select('*').order('name')]);
  if (!course) notFound(); const categories = categoriesData ?? [];
  return <div className="space-y-6"><AdminHeading title={`Edit: ${course.title}`} text="Manage public course content, discovery metadata and structured learning information." /><Panel><form action={updateCourse} className="grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={course.id} />{[['title','Title'],['slug','Slug'],['duration','Duration'],['featured_image','Featured image path or URL'],['og_image','Open Graph image path or URL'],['seo_title','SEO title']].map(([name,label]) => <label key={name} className="grid gap-1 text-sm font-semibold">{label}<input name={name} defaultValue={course[name] || ''} className={inputClass} /></label>)}<label className="grid gap-1 text-sm font-semibold">Category<select name="category_id" defaultValue={course.category_id || ''} className={inputClass}><option value="">No category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="flex items-center gap-2 self-end pb-2 text-sm font-semibold"><input name="is_featured" type="checkbox" defaultChecked={course.is_featured} />Featured course</label><label className="grid gap-1 text-sm font-semibold md:col-span-2">Excerpt<textarea name="excerpt" rows={2} defaultValue={course.excerpt} className={inputClass} /></label><label className="grid gap-1 text-sm font-semibold md:col-span-2">Course overview<textarea name="description" rows={5} defaultValue={course.description} className={inputClass} /></label><label className="grid gap-1 text-sm font-semibold md:col-span-2">SEO description<textarea name="seo_description" rows={3} defaultValue={course.seo_description || ''} className={inputClass} /></label>{[['learning_outcomes','Learning outcomes — one per line'],['requirements','Requirements — one per line'],['who_should_attend','Who should attend — one per line'],['benefits','Benefits — one per line']].map(([name,label]) => <label key={name} className="grid gap-1 text-sm font-semibold">{label}<textarea name={name} rows={6} defaultValue={toLines(course[name])} className={inputClass} /></label>)}<label className="grid gap-1 text-sm font-semibold md:col-span-2">FAQs — JSON array<textarea name="faqs" rows={7} defaultValue={JSON.stringify(course.faqs ?? [], null, 2)} className={`${inputClass} font-mono text-xs`} /></label><button className={`${buttonClass} w-fit`}>Save course</button></form></Panel></div>;
}
