import type { Metadata } from 'next';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { Container } from '@/components/site/container';
import { JsonLd } from '@/components/site/json-ld';
import { getPostBySlug } from '@/lib/content';
import { absoluteUrl, formatDate } from '@/lib/utils';
export async function generateMetadata({params}:{params:{slug:string}}):Promise<Metadata>{const post=await getPostBySlug(params.slug);if(!post)return {};return{title:post.seo_title||post.title,description:post.seo_description||post.excerpt,openGraph:{type:'article',title:post.seo_title||post.title,description:post.seo_description||post.excerpt,images:post.og_image?[post.og_image]:[]},alternates:{canonical:absoluteUrl(`/blog/${post.slug}`)}}}
export default async function BlogPostPage({params}:{params:{slug:string}}){const post=await getPostBySlug(params.slug);if(!post)notFound();const schema={'@context':'https://schema.org','@type':'Article',headline:post.title,description:post.excerpt,datePublished:post.created_at,image:post.featured_image,author:{'@type':'Organization',name:'New Era Computer Training Centre'},publisher:{'@type':'Organization',name:'New Era Computer Training Centre'},mainEntityOfPage:absoluteUrl(`/blog/${post.slug}`)};return <main><JsonLd data={schema}/><section className="border-b border-blue-100 bg-gradient-to-br from-blue-50 via-white to-amber-50"><Container className="py-16"><p className="text-xs font-bold uppercase tracking-wider text-brand-secondary">{formatDate(post.created_at)}</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight text-gray-950 sm:text-5xl">{post.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-gray-600">{post.excerpt}</p></Container></section><article className="py-14"><Container className="max-w-4xl"><Image src={post.featured_image||'/images/blog-generic.svg'} alt="" width={1000} height={580} className="w-full rounded-2xl border border-gray-200"/><div className="prose-content mt-8">{post.content.split('\n\n').map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div></Container></article></main>}
